### ISSUE TITLE
User Crash on Launch

### ISSUE THREAD

**Issue by fzzyhmstrs** [Cosmetica-cc/Cosmetica#124]
**Describe the bug**
One of the players that is trying to Join our SMP had the game crash out on them until Cosmetica was disabled. 

**To Reproduce**
1. This is only happening with certain users. Of about 5 to 7 people I know of that are just trying the pack today, 2 of them have had this issue. One is in Europe somewhere, the other I'm not sure.
2. They haven't done anything specific with Cosmetica or other mods. This crash is happening before they can even fully load in the first time.

**Setup (please complete the following information):**
 - OS: Windows for both of them
 - Minecraft Version: 1.20.1 Fabric
 - Version 1.20-1.2.6

**Log Snippet**
java.lang.IllegalArgumentException: No model for layer minecraft:player#main
	at net.minecraft.client.render.entity.model.EntityModelLoader.getModelPart(EntityModelLoader.java:17)
	at net.minecraft.EntityRendererFactory$Contextclass_5618.getPart(EntityRendererFactory.java:63)
	at cc.cosmetica.cosmetica.screens.fakeplayer.FakePlayer.<init>(FakePlayer.java:56)
	at cc.cosmetica.cosmetica.screens.RSEWarningScreen.init(RSEWarningScreen.java:75)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:297)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient.java:1080)
	at net.minecraft.client.MinecraftClient.handler$cmo000$cosmetica$addRegionSpecificEffectsPrompt(MinecraftClient.java:5049)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient.java)
	at net.minecraft.client.MinecraftClient.onInitFinished(MinecraftClient.java:690)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:674)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**crashlog**
[crash-2023-11-01_17.36.21-client.txt](https://github.com/Cosmetica-cc/Cosmetica/files/13232503/crash-2023-11-01_17.36.21-client.txt)

**Comment by valoeghese** [comment]
This has been fixed as of 1.2.7
