### ISSUE TITLE
Crush when redirect to another server

### ISSUE THREAD

**Issue by Ange8B** [Cosmetica-cc/Cosmetica#126]
crush when redirect to an another server (this bugs happens with sp servers)

1.enter an sp server (i used "play.coralmc.it")
2.try to enter a game and crush when clicking the NPC

**Setup (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.20.2
 - Version: Cosmetica 1.2.6 1.20.2 (hotfix)

the error in the logs while crushing:

[23:17:57] [Render thread/ERROR]:
 Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_640.method_2966()" because the return value of "net.minecraft.class_742.method_3123()" is null
	at net.minecraft.class_742.handler$bdd000$cosmetica$addCosmeticaCapes(class_742.java:1552) ~[client-intermediary.jar:?]
	at net.minecraft.class_742.method_52814(class_742.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3953(class_898.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3950(class_898.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1056) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1113) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:881) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[1.20.2-0.14.24.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]

edit: happened even in hypixel while playing murder mystery, random crush same error

**Comment by valoeghese** [comment]
This was fixed in 1.2.7
