### ISSUE TITLE
Incompatible with Elytra Bombing

### ISSUE THREAD

**Issue by sternschnaube** [Cosmetica-cc/Cosmetica#128]
Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_640.method_2966()" because the return value of "net.minecraft.class_742.method_3123()" is null
	at net.minecraft.class_742.handler$dmg000$cosmetica$addCosmeticaCapes(class_742.java:2052)
	at net.minecraft.class_742.method_52814(class_742.java:68)
	at net.minecraft.class_898.method_3953(class_898.java:97)
	at net.minecraft.class_898.method_3950(class_898.java:131)
	at net.minecraft.class_761.method_22710(class_761.java:1056)
	at net.minecraft.class_757.method_3188(class_757.java:1113)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Client loads fine, when I try to connect to a server it crashes.
Minecraft 1.20.2, Fabric API 0.90.7, Cosmetica 1.2.6+hotfix

https://modrinth.com/mod/elytrabombing
@nad2040

**Comment by nad2040** [comment]
Wow looks like I just spoke too soon. After two minutes, it crashed randomly. Alright.

Looks like these classes are the ones that are causing the problem. I'm not going to bother looking too deep into Cosmetica source code because I have little time, but here are the docs for the first two classes mentioned in the crash.

https://maven.fabricmc.net/docs/yarn-1.20.2+build.1/net/minecraft/client/network/PlayerListEntry.html

https://maven.fabricmc.net/docs/yarn-1.20.2+build.1/net/minecraft/client/network/AbstractClientPlayerEntity.html

**Comment by nad2040** [comment]
Okay I disabled my mod and I waited longer and it still crashed. So I think this issue has nothing to do with my mod.

**Comment by sternschnaube** [comment]
Thanks for the fast answer. Just a random server, it plays no role at this issue.

Mhh, interesting. Removing Elytra Bombing from the client side resolved the crash with Cosmetica for me.
I kept the game running and no crashes at all.

**Comment by Ange8B** [comment]
this is 

> Unreported exception thrown! java.lang.NullPointerException: Cannot invoke "net.minecraft.class_640.method_2966()" because the return value of "net.minecraft.class_742.method_3123()" is null at net.minecraft.class_742.handler$dmg000$cosmetica$addCosmeticaCapes(class_742.java:2052) at net.minecraft.class_742.method_52814(class_742.java:68) at net.minecraft.class_898.method_3953(class_898.java:97) at net.minecraft.class_898.method_3950(class_898.java:131) at net.minecraft.class_761.method_22710(class_761.java:1056) at net.minecraft.class_757.method_3188(class_757.java:1113) at net.minecraft.class_757.method_3192(class_757.java:881) at net.minecraft.class_310.method_1523(class_310.java:1275) at net.minecraft.class_310.method_1514(class_310.java:856) at net.minecraft.client.main.Main.main(Main.java:253) at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 
> Client loads fine, when I try to connect to a server it crashes. Minecraft 1.20.2, Fabric API 0.90.7, Cosmetica 1.2.6+hotfix
> 
> https://modrinth.com/mod/elytrabombing @nad2040

this is the same error i get randomly while playing in some servers, i've already reported it in the issues #126, at first i thought it was related to joining an sp server but later this bug also showed up in hypixel. since i had a quite large modpack i haven't tasted the compatibility with other mods, but I haven't Elytra Bombing in my modpack, so there could be multiple mods that are conflicting somehow.
