### ISSUE TITLE
Crash on Fabric 1.20.2 with latest version 1.2.7 while VPN is active

### ISSUE THREAD

**Issue by sternschnaube** [Cosmetica-cc/Cosmetica#131]
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'cosmetica'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:466)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.JsonParser.parseReader(JsonParser.java:76)
	at com.google.gson.JsonParser.parseString(JsonParser.java:51)
	at com.google.gson.JsonParser.parse(JsonParser.java:115)
	at cc.cosmetica.impl.CosmeticaWebAPI.retrieveAPIIfNoneCached(CosmeticaWebAPI.java:751)
	at cc.cosmetica.impl.CosmeticaWebAPI.newUnauthenticatedInstance(CosmeticaWebAPI.java:699)
	at cc.cosmetica.api.CosmeticaAPI.newUnauthenticatedInstance(CosmeticaAPI.java:500)
	at cc.cosmetica.cosmetica.Cosmetica.onInitializeClient(Cosmetica.java:207)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:71)
	... 13 more

**Comment by valoeghese** [comment]
what do youi see when you go to https://cosmetica.cc/getapi

**Comment by sternschnaube** [comment]
![image](https://github.com/Cosmetica-cc/Cosmetica/assets/120551916/222e555f-b22d-403a-a9d9-3cdf8bcf3d86)

**Comment by sternschnaube** [comment]
Without VPN:

![image](https://github.com/Cosmetica-cc/Cosmetica/assets/120551916/4f9cafaa-45c7-48fb-b5ea-289aa36aab78)

**Comment by sternschnaube** [comment]
Hey ho @valoeghese, everything works now 🥳 
I let this open until you confirmed it final with the close - big thanks!!

**Comment by sternschnaube** [comment]
I have to change my own statement. Some day it works, and the other day it doesn't.

**Comment by Kissunen** [comment]
It started happening again an hour or a few ago. Getting 403 Forbidden with the getapi link and the game just crashes.

**Comment by Kissunen** [comment]
Took like a day or two to get it fixed last time, but as for today, it has started happening again. 403 forbidden with getapi, and the game will crash on launch.

**Comment by sternschnaube** [comment]
Same issues with the 1.20.4 version.

**Comment by Kissunen** [comment]
Still happening today.

Time: 2024-03-02 13:09:40
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'cosmetica'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:466)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.JsonParser.parseReader(JsonParser.java:76)
	at com.google.gson.JsonParser.parseString(JsonParser.java:51)
	at com.google.gson.JsonParser.parse(JsonParser.java:115)
	at cc.cosmetica.impl.CosmeticaWebAPI.retrieveAPIIfNoneCached(CosmeticaWebAPI.java:751)
	at cc.cosmetica.impl.CosmeticaWebAPI.newUnauthenticatedInstance(CosmeticaWebAPI.java:699)
	at cc.cosmetica.api.CosmeticaAPI.newUnauthenticatedInstance(CosmeticaAPI.java:500)
	at cc.cosmetica.cosmetica.Cosmetica.onInitializeClient(Cosmetica.java:207)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:71)
	... 13 more
