### ISSUE TITLE
Error getting user info on startup 

### ISSUE THREAD

**Issue by Nattehine** [Cosmetica-cc/Cosmetica#139]
**Describe the bug**

I use Fabulously Optimized on the curseforge launcher and when I start Minecraft this error happens: 
```
[Cosmetica Lookup Thread #2/ERROR]: Error getting user info for 1c497e7b-2e83-4e94-8474-59652b23ff72 / Nattehine: 
java.io.UncheckedIOException: java.io.IOException: Attempted read from closed stream.
```

Here is the full log: https://pastebin.com/naSzi1DJ

<details>

<summary>While on a server it will also give this error 10 times every ms:</summary>

```
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: java.io.UncheckedIOException: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at cc.cosmetica.api.ServerResponse.<init>(ServerResponse.java:50)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at cc.cosmetica.impl.CosmeticaWebAPI.getCosmeticsPage(CosmeticaWebAPI.java:248)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at cc.cosmetica.impl.CosmeticaWebAPI.getRecentCosmetics(CosmeticaWebAPI.java:258)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at cc.cosmetica.cosmetica.screens.BrowseCosmeticsScreen.lambda$addWidgets$1(BrowseCosmeticsScreen.java:100)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at cc.cosmetica.cosmetica.screens.widget.FetchingCosmetics.lambda$new$0(FetchingCosmetics.java:36)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: Caused by: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:263)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:183)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:242)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:70)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at java.base/java.io.Reader.read(Reader.java:250)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:227)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:270)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at cc.cosmetica.util.Response.getAsJson(Response.java:95)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	at cc.cosmetica.impl.CosmeticaWebAPI.getCosmeticsPage(CosmeticaWebAPI.java:235)
[12:52:30] [Fetching Cosmetics Thread #1/INFO]: [STDERR]: 	... 4 more
```
</details>
It also will not load any cosmetics except Lore.    
  <br/><br/>

**To Reproduce**  
1. Download Fabulously Optimized
2. Add Cosmetica
3. Disable capes-1.5.3+1.20.2-fabric.jar
4. Launch modpack from within the curseforge launcher.

**Expected behavior**
To be able to connect to Cosmetica servers and load cosmetics in-game.

**Screenshots**
N/A

**Setup**
 - OS: Windows 11 with Malwarebytes and NordVPN
 - Intel CPU
 - Nvidia GPU
 - Minecraft Version: 1.20.4
 - Modpack Version: Fabulously Optimized 5.8.0-beta.12
 - Cosmetica Version: 1.2.7

**Additional context**
N/A

**Comment by eyezahhhh** [comment]
This is the result of our current server overload. Don't expect it to work reliably until Cosmetica 2 is released
