### ISSUE TITLE
Please Update to 1.21

### ISSUE THREAD

**Issue by Koekieezz** [Cosmetica-cc/Cosmetica#145]
Please update the mod to 1.21 :D

**Comment by Koekieezz** [comment]
> Official 1.21 port will come in the 2.0 update. For now you can find an unofficial port at https://github.com/MicrocontrollersDev/Cosmetica
> 
> Click on the tick in the latest commit, go to "Summary" then "Artifacts"

Thank you!! When will the 2.0 update come?

**Comment by Koekieezz** [comment]
> Official 1.21 port will come in the 2.0 update. For now you can find an unofficial port at https://github.com/MicrocontrollersDev/Cosmetica
> 
> Click on the tick in the latest commit, go to "Summary" then "Artifacts"
This unofficial port gave me this:
```
[11:36:39] [main/WARN]: Mod resolution failed
[11:36:39] [main/INFO]: Immediate reason: [NEG_HARD_DEP cosmetica 1.2.9 {breaks capes @ [*]}, ROOT_FORCELOAD_SINGLE capes 1.5.4+1.21, ROOT_FORCELOAD_SINGLE cosmetica 1.2.9]
[11:36:39] [main/INFO]: Reason: [NEG_HARD_DEP cosmetica 1.2.9 {breaks capes @ [*]}]
[11:36:39] [main/INFO]: Fix: add [], remove [], replace [[cosmetica 1.2.9] -> add:cosmetica 1 ([(-∞,∞)])]
[11:36:39] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Cosmetica' (cosmetica) 1.2.9 with any version that is compatible with:
		 - capes 1.5.4+1.21
More details:
	 - Mod 'Cosmetica' (cosmetica) 1.2.9 is incompatible with any version of mod 'Capes' (capes), but a matching version is present: 1.5.4+1.21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
```

Are there anything i could do to make it work with capes mod? or it is something from capes mod side?

**Comment by codyisreallycool** [comment]
> > Official 1.21 port will come in the 2.0 update. For now you can find an unofficial port at https://github.com/MicrocontrollersDev/Cosmetica
> > Click on the tick in the latest commit, go to "Summary" then "Artifacts"
> > This unofficial port gave me this:
> 
> ```
> [11:36:39] [main/WARN]: Mod resolution failed
> [11:36:39] [main/INFO]: Immediate reason: [NEG_HARD_DEP cosmetica 1.2.9 {breaks capes @ [*]}, ROOT_FORCELOAD_SINGLE capes 1.5.4+1.21, ROOT_FORCELOAD_SINGLE cosmetica 1.2.9]
> [11:36:39] [main/INFO]: Reason: [NEG_HARD_DEP cosmetica 1.2.9 {breaks capes @ [*]}]
> [11:36:39] [main/INFO]: Fix: add [], remove [], replace [[cosmetica 1.2.9] -> add:cosmetica 1 ([(-∞,∞)])]
> [11:36:39] [main/ERROR]: Incompatible mods found!
> net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
> A potential solution has been determined, this may resolve your problem:
> 	 - Replace mod 'Cosmetica' (cosmetica) 1.2.9 with any version that is compatible with:
> 		 - capes 1.5.4+1.21
> More details:
> 	 - Mod 'Cosmetica' (cosmetica) 1.2.9 is incompatible with any version of mod 'Capes' (capes), but a matching version is present: 1.5.4+1.21!
> 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
> ```
> 
> Are there anything i could do to make it work with capes mod? or it is something from capes mod side?

Remove the `Capes` mod because Cosmetica does the same thing as it, and is incompatible

**Comment by Koekieezz** [comment]
> > > Official 1.21 port will come in the 2.0 update. For now you can find an unofficial port at https://github.com/MicrocontrollersDev/Cosmetica
> > > Click on the tick in the latest commit, go to "Summary" then "Artifacts"
> > > This unofficial port gave me this:
> > 
> > 
> > ```
> > [11:36:39] [main/WARN]: Mod resolution failed
> > [11:36:39] [main/INFO]: Immediate reason: [NEG_HARD_DEP cosmetica 1.2.9 {breaks capes @ [*]}, ROOT_FORCELOAD_SINGLE capes 1.5.4+1.21, ROOT_FORCELOAD_SINGLE cosmetica 1.2.9]
> > [11:36:39] [main/INFO]: Reason: [NEG_HARD_DEP cosmetica 1.2.9 {breaks capes @ [*]}]
> > [11:36:39] [main/INFO]: Fix: add [], remove [], replace [[cosmetica 1.2.9] -> add:cosmetica 1 ([(-∞,∞)])]
> > [11:36:39] [main/ERROR]: Incompatible mods found!
> > net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
> > A potential solution has been determined, this may resolve your problem:
> > 	 - Replace mod 'Cosmetica' (cosmetica) 1.2.9 with any version that is compatible with:
> > 		 - capes 1.5.4+1.21
> > More details:
> > 	 - Mod 'Cosmetica' (cosmetica) 1.2.9 is incompatible with any version of mod 'Capes' (capes), but a matching version is present: 1.5.4+1.21!
> > 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
> > 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
> > 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
> > 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
> > 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Are there anything i could do to make it work with capes mod? or it is something from capes mod side?
> 
> Remove the `Capes` mod because Cosmetica does the same thing as it, and is incompatible

Thankyou, now it is working, but for Shoulder Buddy it always crashes me, what should i do? Here's the crash report

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-07-21 20:23:34
Description: Rendering screen

java.lang.IllegalStateException: Missing elements in vertex: Color
	at net.minecraft.class_287.method_60806(class_287.java:127)
	at net.minecraft.class_287.method_60805(class_287.java:96)
	at net.minecraft.class_287.method_22912(class_287.java:156)
	at cc.cosmetica.cosmetica.screens.widget.SelectableFakePlayers.method_48579(SelectableFakePlayers.java:146)
	at net.minecraft.class_339.method_25394(class_339.java:66)
	at benzenestudios.sulphate.SulphateScreen.method_25394(SulphateScreen.java:330)
	at cc.cosmetica.cosmetica.screens.ApplyCosmeticsScreen.method_25394(ApplyCosmeticsScreen.java:180)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$243(class_757.java)
	at net.minecraft.class_757.wrapOperation$bpj000$fabric-screen-api-v1$onRenderScreen(class_757.java:3586)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_287.method_60806(class_287.java:127)
	at net.minecraft.class_287.method_60805(class_287.java:96)
	at net.minecraft.class_287.method_22912(class_287.java:156)
	at cc.cosmetica.cosmetica.screens.widget.SelectableFakePlayers.method_48579(SelectableFakePlayers.java:146)
	at net.minecraft.class_339.method_25394(class_339.java:66)
	at benzenestudios.sulphate.SulphateScreen.method_25394(SulphateScreen.java:330)
	at cc.cosmetica.cosmetica.screens.ApplyCosmeticsScreen.method_25394(ApplyCosmeticsScreen.java:180)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$243(class_757.java)
	at net.minecraft.class_757.wrapOperation$bpj000$fabric-screen-api-v1$onRenderScreen(class_757.java:3586)

-- Screen render details --
Details:
	Screen name: cc.cosmetica.cosmetica.screens.ApplyCosmeticsScreen
	Mouse location: Scaled: (541, 302). Absolute: (1082.000000, 604.000000)
	Screen size: Scaled: (960, 505). Absolute: (1920, 1009). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 3957.035s
	Wall uptime: 3947.805s
	High-res time: 58850.516s
	Client ticks: 77956 ticks / 3897.800s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by codyisreallycool** [comment]
> Thankyou, now it is working, but for Shoulder Buddy it always crashes me, what should i do? Here's the crash report

I crash when changing shoulder buddies as well, I'd suggest using Cosmetica with 1.20 to change them, and then using the 1.21 port just to have them be shown

**Comment by OrdinaryCloverOC** [comment]
> Official 1.21 port will come in the 2.0 update. For now you can find an unofficial port at https://github.com/MicrocontrollersDev/Cosmetica
> 
> Click on the tick in the latest commit, go to "Summary" then "Artifacts"

https://codeberg.org/MicrocontrollersDev/Cosmetica/releases they moved to codeberg since then.

**Comment by sternschnaube** [comment]
Hello @valoeghese, any update on 1.21.4? 😊

**Comment by valoeghese** [comment]
1.21.4 changes a lot under the hood for modders doing rendering. I looked into updating Cosmetica 1 to it but I figure it will be more beneficial to just work on Cosmetica 2.0, since I can prepare the codebase to be more version agnostic in advance before I port *that* to 1.21

**Comment by valoeghese** [comment]
As for 1.21/1.21.1, I've officially endorsed MicrocontrollersDev's port and uploaded it to our modrinth, with his consent

**Comment by sternschnaube** [comment]
Thanks for the clarification, really missing to play with it yet 😄

It will be good when it's done.
