### ISSUE TITLE
Crash when enter in the world

### ISSUE THREAD

**Issue by lostopkk** [Cosmetica-cc/Cosmetica#59]
**Describe the bug**
when I go to enter my modpack it is 100% to load the world, it gives errors in the log, and it never enters!

**Expected behavior**
enter the world

**Setup (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version: 1.19.2

**Log**
[2022-09-12-1.log](https://github.com/EyezahMC/Cosmetica/files/9552240/2022-09-12-1.log)

**Comment by craftish37** [comment]
This looks like an other mod’s error, you seems to have a lot of 'em so proceed via binary search, this will help you to find the problem 👀

![](https://c.tenor.com/Jl0YrqxnHmAAAAAd/binary-search-sequence-search.gif)

**Comment by lostopkk** [comment]
> This looks like an other mod’s error, you seems to have a lot of 'em so proceed via binary search, this will help you to find the problem 👀
> 
> ![](https://camo.githubusercontent.com/e7c5471862f73d615d50037b6f87120357daaeefe5c88a21a70cb952f9ac5ad0/68747470733a2f2f632e74656e6f722e636f6d2f4a6c30597271786e486d4141414141642f62696e6172792d7365617263682d73657175656e63652d7365617263682e676966) [ ![68747470733a2f2f632e74656e6f722e636f6d2f4a6c30597271786e486d4141414141642f62696e6172792d7365617263682d73657175656e63652d7365617263682e676966](https://camo.githubusercontent.com/e7c5471862f73d615d50037b6f87120357daaeefe5c88a21a70cb952f9ac5ad0/68747470733a2f2f632e74656e6f722e636f6d2f4a6c30597271786e486d4141414141642f62696e6172792d7365617263682d73657175656e63652d7365617263682e676966) ](https://camo.githubusercontent.com/e7c5471862f73d615d50037b6f87120357daaeefe5c88a21a70cb952f9ac5ad0/68747470733a2f2f632e74656e6f722e636f6d2f4a6c30597271786e486d4141414141642f62696e6172792d7365617263682d73657175656e63652d7365617263682e676966) [ ](https://camo.githubusercontent.com/e7c5471862f73d615d50037b6f87120357daaeefe5c88a21a70cb952f9ac5ad0/68747470733a2f2f632e74656e6f722e636f6d2f4a6c30597271786e486d4141414141642f62696e6172792d7365617263682d73657175656e63652d7365617263682e676966)

that's what I did, and it went to cosmetica, if not, I wouldn't have made the issue... it was literally when I took the mod out my modpack went back to working normally

**Comment by valoeghese** [comment]
The only error I can see from cosmetica is ```java
[19:24:07] [Cosmetica Authenticator #1/ERROR]: Couldn't connect to cosmetica auth server
java.io.IOException: Attempted read from closed stream.
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:176) ~[httpcore-4.4.14.jar:?]
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135) ~[httpclient-4.5.13.jar:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:177) ~[?:?]
	at java.io.Reader.read(Reader.java:250) ~[?:?]
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:227) ~[httpcore-4.4.14.jar:?]
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:270) ~[httpcore-4.4.14.jar:?]
	at cc.cosmetica.util.Response.getAsJson(Response.java:95) ~[com_github_cosmetica-cc_cosmetictjava-1.5.2-aa23a66a5394fee0.jar:?]
	at cc.cosmetica.impl.CosmeticaWebAPI.exchangeTokens(CosmeticaWebAPI.java:66) ~[com_github_cosmetica-cc_cosmetictjava-1.5.2-aa23a66a5394fee0.jar:?]
	at cc.cosmetica.impl.CosmeticaWebAPI.<init>(CosmeticaWebAPI.java:53) ~[com_github_cosmetica-cc_cosmetictjava-1.5.2-aa23a66a5394fee0.jar:?]
	at cc.cosmetica.impl.CosmeticaWebAPI.fromMinecraftToken(CosmeticaWebAPI.java:588) ~[com_github_cosmetica-cc_cosmetictjava-1.5.2-aa23a66a5394fee0.jar:?]
	at cc.cosmetica.api.CosmeticaAPI.fromMinecraftToken(CosmeticaAPI.java:366) ~[com_github_cosmetica-cc_cosmetictjava-1.5.2-aa23a66a5394fee0.jar:?]
	at cc.cosmetica.cosmetica.Authentication$1.run(Authentication.java:166) [Cosmetica%201.2.1%201.19.1.jar:?]
```

**Comment by valoeghese** [comment]
the only reason I can see cosmetica causing an error here is if it's conflicting with one of the mods. And that's a lot of mods to test with

**Comment by lostopkk** [comment]
> the only reason I can see cosmetica causing an error here is if it's conflicting with one of the mods. And that's a lot of mods to test with

well my computer is not very good for me to be able to keep taking them one by one to find out which one is conflicting, so would I think I better close the issue?

**Comment by eyezahhhh** [comment]
Closing cos nobody knows what's going on lol.
